/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BusinessInfo {
  'instagram' : string,
  'name' : string,
  'facebook' : string,
  'address' : string,
  'phone' : string,
}
export interface MenuCategory { 'title' : string, 'items' : Array<MenuItem> }
export interface MenuItem {
  'name' : string,
  'description' : string,
  'badge' : [] | [string],
  'price' : bigint,
}
export interface SpecialOffer { 'title' : string, 'description' : string }
export interface _SERVICE {
  'getAllCategories' : ActorMethod<[], Array<MenuCategory>>,
  'getBusinessInfo' : ActorMethod<[], BusinessInfo>,
  'getMenuCategory' : ActorMethod<[string], MenuCategory>,
  'getSpecialOffer' : ActorMethod<[], SpecialOffer>,
  'initializeMenu' : ActorMethod<[], undefined>,
  'updateBusinessInfo' : ActorMethod<[BusinessInfo], undefined>,
  'updateMenuCategory' : ActorMethod<[string, MenuCategory], undefined>,
  'updateSpecialOffer' : ActorMethod<[SpecialOffer], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];