/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'badge' : IDL.Opt(IDL.Text),
  'price' : IDL.Nat,
});
export const MenuCategory = IDL.Record({
  'title' : IDL.Text,
  'items' : IDL.Vec(MenuItem),
});
export const BusinessInfo = IDL.Record({
  'instagram' : IDL.Text,
  'name' : IDL.Text,
  'facebook' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const SpecialOffer = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllCategories' : IDL.Func([], [IDL.Vec(MenuCategory)], ['query']),
  'getBusinessInfo' : IDL.Func([], [BusinessInfo], ['query']),
  'getMenuCategory' : IDL.Func([IDL.Text], [MenuCategory], ['query']),
  'getSpecialOffer' : IDL.Func([], [SpecialOffer], ['query']),
  'initializeMenu' : IDL.Func([], [], []),
  'updateBusinessInfo' : IDL.Func([BusinessInfo], [], []),
  'updateMenuCategory' : IDL.Func([IDL.Text, MenuCategory], [], []),
  'updateSpecialOffer' : IDL.Func([SpecialOffer], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'badge' : IDL.Opt(IDL.Text),
    'price' : IDL.Nat,
  });
  const MenuCategory = IDL.Record({
    'title' : IDL.Text,
    'items' : IDL.Vec(MenuItem),
  });
  const BusinessInfo = IDL.Record({
    'instagram' : IDL.Text,
    'name' : IDL.Text,
    'facebook' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SpecialOffer = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllCategories' : IDL.Func([], [IDL.Vec(MenuCategory)], ['query']),
    'getBusinessInfo' : IDL.Func([], [BusinessInfo], ['query']),
    'getMenuCategory' : IDL.Func([IDL.Text], [MenuCategory], ['query']),
    'getSpecialOffer' : IDL.Func([], [SpecialOffer], ['query']),
    'initializeMenu' : IDL.Func([], [], []),
    'updateBusinessInfo' : IDL.Func([BusinessInfo], [], []),
    'updateMenuCategory' : IDL.Func([IDL.Text, MenuCategory], [], []),
    'updateSpecialOffer' : IDL.Func([SpecialOffer], [], []),
  });
};

export const init = ({ IDL }) => { return []; };