/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MenuItem {
    name: string;
    description: string;
    badge?: string;
    price: bigint;
}
export interface MenuCategory {
    title: string;
    items: Array<MenuItem>;
}
export interface SpecialOffer {
    title: string;
    description: string;
}
export interface BusinessInfo {
    instagram: string;
    name: string;
    facebook: string;
    address: string;
    phone: string;
}
export interface backendInterface {
    getAllCategories(): Promise<Array<MenuCategory>>;
    getBusinessInfo(): Promise<BusinessInfo>;
    getMenuCategory(category: string): Promise<MenuCategory>;
    getSpecialOffer(): Promise<SpecialOffer>;
    initializeMenu(): Promise<void>;
    updateBusinessInfo(newInfo: BusinessInfo): Promise<void>;
    updateMenuCategory(category: string, newCategory: MenuCategory): Promise<void>;
    updateSpecialOffer(newOffer: SpecialOffer): Promise<void>;
}
import type { MenuCategory as _MenuCategory, MenuItem as _MenuItem } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllCategories(): Promise<Array<MenuCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCategories();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCategories();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBusinessInfo(): Promise<BusinessInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusinessInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusinessInfo();
            return result;
        }
    }
    async getMenuCategory(arg0: string): Promise<MenuCategory> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuCategory(arg0);
                return from_candid_MenuCategory_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuCategory(arg0);
            return from_candid_MenuCategory_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSpecialOffer(): Promise<SpecialOffer> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpecialOffer();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpecialOffer();
            return result;
        }
    }
    async initializeMenu(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeMenu();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeMenu();
            return result;
        }
    }
    async updateBusinessInfo(arg0: BusinessInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBusinessInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBusinessInfo(arg0);
            return result;
        }
    }
    async updateMenuCategory(arg0: string, arg1: MenuCategory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuCategory(arg0, to_candid_MenuCategory_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuCategory(arg0, to_candid_MenuCategory_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSpecialOffer(arg0: SpecialOffer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSpecialOffer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSpecialOffer(arg0);
            return result;
        }
    }
}
function from_candid_MenuCategory_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuCategory): MenuCategory {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_MenuItem_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuItem): MenuItem {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    items: Array<_MenuItem>;
}): {
    title: string;
    items: Array<MenuItem>;
} {
    return {
        title: value.title,
        items: from_candid_vec_n4(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    badge: [] | [string];
    price: bigint;
}): {
    name: string;
    description: string;
    badge?: string;
    price: bigint;
} {
    return {
        name: value.name,
        description: value.description,
        badge: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.badge)),
        price: value.price
    };
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MenuCategory>): Array<MenuCategory> {
    return value.map((x)=>from_candid_MenuCategory_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MenuItem>): Array<MenuItem> {
    return value.map((x)=>from_candid_MenuItem_n5(_uploadFile, _downloadFile, x));
}
function to_candid_MenuCategory_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuCategory): _MenuCategory {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_MenuItem_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuItem): _MenuItem {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    badge?: string;
    price: bigint;
}): {
    name: string;
    description: string;
    badge: [] | [string];
    price: bigint;
} {
    return {
        name: value.name,
        description: value.description,
        badge: value.badge ? candid_some(value.badge) : candid_none(),
        price: value.price
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    items: Array<MenuItem>;
}): {
    title: string;
    items: Array<_MenuItem>;
} {
    return {
        title: value.title,
        items: to_candid_vec_n10(_uploadFile, _downloadFile, value.items)
    };
}
function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<MenuItem>): Array<_MenuItem> {
    return value.map((x)=>to_candid_MenuItem_n11(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
